### ISSUE TITLE
RunUntilRet event handler stops on syscalls

### ISSUE THREAD

**Issue by Northern-Lights** [eteran/edb-debugger#145]
When using the "Run Until Return" function, it appears that the RunUntilRet event handler passes control back to the Debugger event handler after returning from a syscall.  I haven't been able to spot the underlying root cause, but after the syscall, it looks like
`event->trap_reason()`
returns IDebugEvent::TRAP_BREAKPOINT, causing the handler to pass the event to the Debugger handler which returns edb::DEBUG_STOP, ending the RunUntilRet.

Usually if "Run Until Return" is executed from user code, the correct `ret` is found, I suppose because all of the calls are standard and get stepped over.  I have mainly seen this issue when trying to ret from library code.

I've poked around with the code and tried some quick-fixes, including "if the previous instruction was a syscall, then try to step over", but it throws some exception that causes Qt to abort.  Could this happen if we hit a `syscall exit` with the quick-fix condition?

**Comment by eteran** [comment]
Yes, this is something that I noticed in the past and honestly wasn't 100% sure what the ideal fix is. I just got back from a weekend trip, now that I'm back, I'm sure we can figure out a workable solution :-).

**Comment by Northern-Lights** [comment]
I tried the following logic as an alternative:
```
if current instruction is not ret
    put a breakpoint on the next instruction
    return edb::DEBUG_CONTINUE
```
It seems like it would work, except for the fact that when we get the state on the next handle_event(), IP has advanced 1 address too far.  For example, if we had instructions on these addresses:
1
4
6
Then say we initiated the Run Until Return at 1.  The event handler hits 4 just fine (the event reason is "tracing" here).  But when the breakpoint is set on 6 and edb::DEBUG_CONTINUE is returned, then on the next handle_event(), we are at 7 (in the middle of the instruction at 6).
Do you have any ideas as to why the IP is being advanced 1 further than it should be?

**Comment by eteran** [comment]
So, I've been putting some thoughts into this, and I have a plan :-).

instead of stepping one by one until we hit the ret. We instead scan ahead to the first basic block terminator (hlt/ret/jmp/jcc/etc). We put a breakpoint on that and then run. if we stopped on a ret, good we're done. If we didn't, repeat. This should actually be faster than the original code too.

I think that this should fairly seamlessly fix the issue.

**Comment by Northern-Lights** [comment]
I tested that out (you can see my change in my testing branch: a340cb142d46ee3c690976cd71dc8d390ae67ea7).  Unfortunately, it's suffering from the same issue I mentioned above: when we get the next event after an edb::DEBUG_CONTINUE, our execution address (RIP) gets incremented by 1 which throws off our ability to get the correct instructions.

Another potential caveat that would affect my solution above, as wel: what if we have the following situation:

1 add
2 sub
3 sub
**4 jmp 2**
5 add
6 ret

Say we started Run Until Ret at address 1.  We put our breakpoint on 4, run, break, find the next ret-ish instruction at 6, set the breakpoint, and run again...  But the jump takes us away from the breakpoint, instead.

So in all, I'm seeing 2 things stand in our way:
1. A syscall gives a trap reason of IDebugEvent::TRAP_BREAKPOINT, preventing us from stepping properly.
2. Returning edb::DEBUG_CONTINUE within the event handler causes the RIP to be 1-off on the next event, preventing us from making use of any breakpoints.

**Comment by eteran** [comment]
So your example is interesting because it *never* returns. But let's ignore that for a second :-).

1. The scanning forward would have to be inclusive if the instruction you're on. This is illustrated by the fact that a branch target can itself be a basic block terminator. Think of jmps whose targets are also jmps and such.

2. There is code in in edb (I am fairly certain) for dealing with the "I want to resume but I'm sitting on a breakpoint" issue. It's annoying since there are corner cases such as:

        1: jz 1 ; infinite loop if the Z flag is 0!

    What the code has to do is:
    1. unset the breakpoint
    2. set on instruction.
    3. reset the breakpoint
    4. attempt a run, which may just land on the same breakpoint if where' in a loop!

I've got some unrelated changes in the pipeline, but I would love to get this feature working bug free! See please don't get discouraged, I'll keep thinking about how to best deal with it too! 

Anyway, take a look at `Debugger::resume_execution`. It was a bit of a nightmare to implement and I'd love the simplify it eventually, but it implements the concept outlined above :-).

**Comment by Northern-Lights** [comment]
1. I think that would be ok if we single-step on any type of branch.  Just do a single step, and then scan forward to the next block terminator.  If you're on a jmp, single-step, and if you hit another jmp, just single-step again.

I'm still a bit stuck on why syscalls cause `IDebugEvent::TRAP_BREAKPOINT`.  Additionally, and maybe a bigger flaw, I don't why `edb::DEBUG_CONTINUE` causes the RIP to be set 1 higher than it should be.  How would one go about debugging something like this?  It just seems like magic to me in between events.

Oh, don't worry about me getting discouraged...  Frustrated - maybe - but as long as we solve the problem, it's worth it :)

**Comment by eteran** [comment]
So the system call causing a `IDebugEvent::TRAP_BREAKPOINT` I believe is just a quirk in Linux's ptrace.

As for `edb::DEBUG_CONTINUE` causing `RIP` to be off by one. I'd have to look into it further to figure it out. Perthaps even see it in action :-/. It's always difficult to debug these types of things indirectly. I'll take a look at the code and see if anything stands out.

**Comment by eteran** [comment]
I've being thinking about the "off by one" issue. I believe that it is actually the expected behavior. Here's what's going on (I think).

When you set a software breakpoint, you are replacingthe first byte of the instruction with an `int3` (one byte). When the CPU hits that address, it **executes**, the breakpoint instruction, this of course creates an OS level exception, which is trapped by the kernel and eventually reported to the debugger. But the point is, it executes the `int3`, meaning that the IP will be at the "next" instruction...1 byte past the breakpoint :-).

If we look in edb's code, specifically `Debugger::handle_trap` there is code which addresses this. It looks at the (IP - 1) and if there is a known BP there, will backup the IP as needed. And potentially update the BP information.

The run until return code will want to use similar logic. Hope this helps :-)

**Comment by Northern-Lights** [comment]
Ok, the int 3 makes a lot of sense.  I've made changes here that support that: 183ddb8eae7b8c290f9a652e40c5b5216d1b2700

The logic gets very complicated because there are so many exceptions (like the syscall causing TRAP_BREAKPOINT, among other things.)  I'm not sure if I covered every possible scenario.

I had a few crashes at first because I guess I didn't consider IDebugEvent::REASON, e.g. EXITED or TERMINATED.  From what I have seen, RIP will == 0 when we get those event reasons, so I'm wondering if simply checking address == 0 is enough to say "the process has terminated/exited/otherwise ended"

One weak point that I'm seeing through this method is if there are invalid instructions ahead, then we will be unable to find a block terminator, and therefore I just pass everything back to the previous handler.

**Comment by eteran** [comment]
I think that as long as we do the algorithm that runs until a BP (at the end of the basic block) instead of stepping, then the syscall issue shouldn't be a problem at all. I believe that only happens when we step while on a system call (which is not a basic block terminator, so that shouldn't happen).

The way that I see it, if there are invalid instructions in the stream. We can just report it to the user saying "Unable To Run Until Return Instruction" or something similar. This should basically never happen though since any invalid instruction would crash the debugged application anyway. Keep in mind, the look ahead shouldn't actually follow branches, we let the actual execution of the application do that. So only valid code paths will even be considered.

**Comment by Northern-Lights** [comment]
I have a new algorithm that should work regardless of being on a syscall.  The changelist is here: 183ddb8eae7b8c290f9a652e40c5b5216d1b2700

What I'm trying to do is:
1. Scan ahead for a block terminator
2. Set a breakpoint there and run
3. If it's an internal breakpoint and we're on a ret, pass the event handler back to the Debugger
4. If it's an internal breakpoint and we're NOT on a ret, then single-step and repeat
(3. and 4. both decrement RIP by 1 to accommodate having executed the 0xcc breakpoint).

That's not the complete story, as you can see in the code; there are a lot of other checks.  It's a total mess, but it appears to work for rets but not jmps/jccs.  I can't figure out why when I try to single-step on the jmp/jcc, the next event does NOT take into effect my RIP--.  See the changelist for my comments on the line where the code is: 183ddb8eae7b8c290f9a652e40c5b5216d1b2700

If you have any ideas as to why the RIP adjustments don't take effect for `edb::DEBUG_CONTINUE_STEP`, it would help a lot.

**Comment by eteran** [comment]
Very cool, that's very close to the algorithm that I was imagining. But I think you've done a great job of identifying the corner cases.

I'll definitely take a look and see why the RIP update is not being seen in some cases.

Thanks!

**Comment by Northern-Lights** [comment]
Just a quick update: I added a line right before the `edb::DEBUG_CONTINUE_STEP` to allow the previous handler to handle such events (where we're on a breakpoint, and then we want to step), since this is how you appear to handle the `IDebugEvent::TRAP_BREAKPOINT` case in the original RunUntilRet.

The new change is here: 04f9bd0c0fe20930182ffd6ba4d507b49b2a5878

Maybe I just have the wrong idea of thinking that returning `edb::DEBUG_CONTINUE_STEP` means that we will step 1 instruction wherever RIP is set?

**Comment by eteran** [comment]
Hmm, returning `DEBUG_CONTINUE_STEP` should result in execution being resumed for one instruction. "Where", should be at RIP. I'll have to look more at your patches, but you will need to set the state after modifying the state object to make sure that it is "commited". In the end, I do think that your fix will work since calling the old handler will in effect cause all of that to happen. (It will eventually call `handle_trap` which eventually executes this code:

		// back up eip the size of a breakpoint, since we executed a breakpoint
		// instead of the real code that belongs there
		state.set_instruction_pointer(previous_ip);
		edb::v1::debugger_core->set_state(state);

which will set the state in the process appropriately.

**Comment by eteran** [comment]
Looking at your previous patches, I think that I have confirmed that this is the problem. Basically when you call `state.set_instruction_pointer(x)`. That is setting the value of IP in the state object. But that's just a local variable. It doesn't do anything to the process unless `edb::v1::debugger_core->set_state(state);` is called afterwards.

I can understand how this could be confusing. I'll explain the mentality.

`State` objects are just copies of the current thread/process state. The functions to set/get registers simply read/write that local copy. Things like `set_instruction_pointer` are an attempt at maximizing portability. I don't want you to have to write:

    #if defined(x86)
        state.set("eip", x);
    #else if defined(x86_64)
        state.set("rip", x);
    #else
        ...
    #endif

So it is abstracted a bit.

I hope this helps.

**Comment by Northern-Lights** [comment]
That makes sense, although I'm not sure why it was still working well for `ret` instructions.

After doing what you suggested, I was still seeing issues with jmp/jcc.  I think it was due to improper handling of the breakpoint byte.  Maybe it was ok for `ret` since it is only 1 byte, but jmp/jcc were infinite-looping.  So now I'm logging a hit when the breakpoint is hit, and I disable and remove the breakpoint if it is internal.  (If I don't remove it through `edb::v1::debugger_core->remove_breakpoint()`, then the breakpoint symbol still shows up in the UI, even though it should be internal; it doesn't show up in the BreakpointManager plugin, ironically.)

You can take a look at the latest change here: 2055fb728bef5702df58e0985c93bb60b55c0d20
Any comments are welcome.  I want to do some more testing before considering this issue/feature/enhancement complete, but it looks like we're on the right path :)  Thanks for your help.

**Comment by eteran** [comment]
I think this issue is generally resolved. Thanks Northern-Lights :-)

**Comment by Northern-Lights** [comment]
Excellent!
