### ISSUE TITLE
REplace edassm by capstone.

### ISSUE THREAD

**Issue by ret5et** [eteran/edb-debugger#153]
Replace edassm by [capstone](https://github.com/aquynh/capstone).

**Comment by eteran** [comment]
Is there a feature that you feel Capstone has that would make the effort of the switch worth it?

**Comment by ret5et** [comment]
This is only my IMHO:
Сapstone mote mature than edassm. And I think Сapstone can prevent from bugs as #152.
Capstone can dissasm many platforms - arm, mips, etc. Can we use capstone as plugin?
In future edb-debugger + capstone + gdbserver + script_engine = super_power_tool for dynamic re.

**Comment by eteran** [comment]
I am not specifically against using capstone. Certainly, using it would help avoid incorrect disassembly listings (Fortunately, they've been rare).

I will look into making the disassembly engine a plugin, then it'll be a choice.

As far as multiple platforms, first the core would have to support them, doable, but will need some work. I will leave this bug open for now since I am not "closing the door" on this request.

**Comment by 10110111** [comment]
Might making use of capstone be simpler than implementation of AVX/AVX2 instruction support?

**Comment by eteran** [comment]
Yes, in general since Capstone is a well supported, stand alone product. It will be easier for them to keep up to date with newer arches. That is probably the most realistic argument for switching away from the proprietary disassembler.

**Comment by 10110111** [comment]
I'm currently half-way at making a proof of concept wrapper of Capstone for EDB, and I've found out that Capstone is actually not that great in some things.

* First, it doesn't appear to provide a way to get opcode length and total length of all prefixes. It'll either need to be done in the wrapper, or just not implemented at all. In particular, for EDB this means a need to switch the user code to another ways of checking `Jcc` codes — it'll be more verbose although somewhat easier to read.

* Next, it doesn't register mandatory prefixes in its detail structure. Namely, for instruction like

    F3 0F E6 90 90 90 90 90    cvtdq2pd xmm2, qword [rax-0x6f6f6f70]

 it registers only `0F E6` in its opcode bytes, but doesn't register `F3` mandatory prefix in its prefix bytes.

* Also it differs in mnemonics of some instructions, e.g. `movabs` instead of `mov` for `48 B8+r imm64` (although this particular example might be a plus, since it disambiguates `mov r64, imm32` from `mov r64, imm64`).

Anyway, I think I'll try to finish the implementation and see what I get. Capstone still has some useful features (even not considering other arches than x86* for now) like support for most (all?) of current instruction set extensions, dynamic switching of bitness (a matter of `cs_open/cs_close` calls), dynamic selection of Intel or AT&T syntax etc..

**Comment by eteran** [comment]
This is fantastic! I can't wait to see what you've come up with. Are you creating a wrapper which has the same interface as `edb::Instruction`? Or are you refactoring the code which used it?

I am hoping in the long run to come up with a strategy to efficiently support the disassembly engine being a plugin. Your work is likely a huge step in that direction :-).

As usual, thanks so much for your efforts.

**Comment by 10110111** [comment]
I'm trying to follow the interface of edisassm as much as possible, but I still do have to make some changes to user code, because 1) I don't want to repeat (e.g. create an enum which just assigns its values to those of Capstone for `Instruction::Type`) and 2) Capstone interface itself a bit somewhat different.

**Comment by eteran** [comment]
Makes sense. Very excited to see how it works :-)

**Comment by 10110111** [comment]
You can see early alpha version in my [capstone branch](https://github.com/10110111/edb-debugger/tree/capstone). There're still many bugs, and some things are not yet implemented, but at least it doesn't instantly crash already :)

**Comment by eteran** [comment]
Thanks to the hard work of 10110111, capstone is now the disassemble in edb!
