### ISSUE TITLE
`int 0x80` is disassembled as `int 0xffffff80`

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#183]
The `int 0x80` instruction is `CD 80`, but is disassembled as `int 0xffffff80`. Apparently, along with #179, this was introduced by the same set of changes.

**Comment by eteran** [comment]
sigh, the "sometimes" sign extend, sometimes don't is proving to be difficult :-/. I was seeing things like:

`and rsp, 0x80` (the byte version) being diusassembled as: `and rsp, 0xffffffffffffff80`.

So it seems almost arbitrary which ops do and don't. Oh well, I'll look into the best way to fix it!

**Comment by 10110111** [comment]
Why not just print them as signed types of correct size? This seems to be workable, although `char`s will need special treatment if using `ostream` for this.

**Comment by eteran** [comment]
you mean like in decimal? If so, I don't think that's preferable since all other things show in hex. Otherwise, I'm not 100% sure what you mean. If there is an instruction which says `and rsp, 0x80`, it really means `and rsp, 0xffffffffffffff80`. So as per previous things in the issue tracker, it should be displayed as such. Right?

**Comment by 10110111** [comment]
No, I mean hex, but if you currently use `operator<<(ostream&,uintXX_t)`, you might have better luck with `operator<<(ostream&,intXX_t)`, notice `int` instead of `uint` here. This will still work with `std::hex`, giving you e.g. `0xfffffffffffffff0` for `-16LL`.

**Comment by eteran** [comment]
ok, I'll check it out. I still think that the "sometimes" widen sbyte and sometimes don't is going to need special treatment though. We'll see ;-)

**Comment by 10110111** [comment]
> If there is an instruction which says and `rsp, 0x80`, it really means and `rsp, 0xffffffffffffff80`.

Noo, there's no instruction which does this. There are some instructions which e.g. have a four-byte immediate but imply sign extension to 64 bits, but this is just their encoding, not something what users of a disassembler API want to know. The operand should be sign-extended at the stage of disassembly, and then to the API users the instruction should seem to mean what it really means.

**Comment by eteran** [comment]
Hmm, You may be right, it's possible that I've confused some details since it's a been a LONG time since I was heavily working on the disassembly engine. Anyway, when looking at the intel manual I see things like this in the logical AND section:

    REX + 20 /r AND r/m8*, r8* MR Valid N.E. r/m64 AND r8 (sign-extended).

Doesn't that mean that the 8-bit immediate is sign extended? I'll try to find a specific example

**Comment by eteran** [comment]
Ah, here's an example of what I'm thinking of:

    48 83 e4 ff

Which at least some sources claim decodes as:

    [and rsp, 0xffffffffffffffff](https://www.onlinedisassembler.com/odaweb/QZeYo88C/0)

So, internally, it is an 8-bit immediate, but it is actually supposed to be sign extended out to 32/64 bits.

**Comment by eteran** [comment]
So, i think i know what the best solution is... but it's gonan be a pain. Write now I have functions in edisassm like:

    decode_Ib // byte immediate
    decode_Iw // word immediate
    decode_Id // dword immediate
    decode_Iq // qword immediate (not sure if these exist, but I have support)

I'll probably need to make a variant for signed ones, which will explicitly know to sign extend (or not). Then I just need to update the tables and it should be all good.

**Comment by eteran** [comment]
OK, so I've just done a commit which puts things in a better place (and fixes THIS particular bug). Before sign extension was being done at format time and the decoding was storing just the literal immediate. This made things difficult since at format time, it was impossible to know if the op should be sign extended, but it is something that is known at decode time.

So, the new approach is that there are decode functions which sign extend, and some which don't and I'll have to update the tables as I find mistakes.

All in all, not a terribly fun task, but it'll allow me to fix these bugs easily as they are found :-).

Thanks as usual Ruslan!

**Comment by 10110111** [comment]
You can easily find which instructions should sign extend by just searching for `sign extended` in Intel's Instruction Set Reference.
