### ISSUE TITLE
Some assembly codes are not accepted by EDB even though they are valid for the assembler

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#259]
To reproduce:
1. Open Assemble dialog
2. Enter `loop $`
3. Press Enter
4. See "Error In Code" message, which doesn't give any clue as to what error it found
5. Check with the assembler (`yasm` by default) that the code is valid:
````
$ echo 'loop $' > test.asm
$ yasm test.asm -o test.bin
$ xxd -g1 test.bin
0000000: e2 fe

**Comment by eteran** [comment]
Ah, this is likely (almost certainly) the regex based normalization code. I am a bit torn on whether or not to keep it or ditch it completely.

On one hand, it would be really nice if any time you open the assembler, the disassembled instruction was immediately assemble-able, but that won't work in the general case because `yasm` and `nasm` have a slightly different syntax than Capstone. So we try to "fix it up" before handing it off.

On the other hand, we (nearly) have generalized support for ANY assembler, so why limit what you can type to one syntax. It does generally make sense to just hand it off to the assembler and let it do what it wants to do.

Like I said, I'm a bit  undecided on how to "fix" this one. Both approaches have a downside.

**Comment by eteran** [comment]
The only think that I can think of that would be an "exhaustive" solution, would look like this:

1. if the regexes don't match, it's a good chance that it's because the user **typed** some code, not disassembled, so we should just let it pass through (this we can do immediately to address **this** bug.

2. it the XML file, allow the user to specify some script or regex to normalize to a common syntax. Like "here's what an expression looks like", "here's what segment usage looks like", etc... But this gets **really** messy quickly, especially if we start to support non-x86 family processors.

**Comment by 10110111** [comment]
In fact, the instruction might be assemblable, but not to the current bytes. Consider e.g. `FF C8` vs `48`. Both are `dec eax`, but you won't get the former (in 32-bit mode) after re-assembly.
Also, i expect this to fail when an assembler wants AT&T syntax, while EDB shows Intel disassembly.

Anyway, why not just check that the user **did type** something?

**Comment by eteran** [comment]
You are right on both accounts. I've run into "it assembles, but is different often with things like `push 0xffffffffffffffff`, where the assembler really wants to output a much larger immediate instead of what the original code had which was a small value sign extended to stack width.

AT&T is a whole different beast (though would be addressable with the regex/scripting concept).

I've got a quick fix incoming. Basically, we try to fix up, if we fail, well, we'll send it to the assembler anyway :-)

**Comment by eteran** [comment]
`loop $` now assembles correctly :-D

**Comment by 10110111** [comment]
I'm a bit worried about whether this normalization magic will transform an instruction the user typed into a completely different instruction. Is this possible?

**Comment by eteran** [comment]
I don't **think** there are any cases where that could happen, but I could be wrong. It is definitely something we should definitely look out for.
