### ISSUE TITLE
Conditional breakpoints don't work

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#260]
Namely, if you make the code `B9 45 23 01 00 90 90 90 E2 FB`, then put a conditional breakpoint at the third `NOP` with condition of `ecx==127`, then press `F9`, don't try to wait until it fires :) . It sticks at the breakpoint and moves no further.

**Comment by eteran** [comment]
does that code set `ecx` to `0x12345`? why would the BP fire. I'm not seeing what's wrong.

**Comment by eteran** [comment]
Hmm, even with the condition of `ecx == 0x12345`, it does not seem to work... you have my attention :-).

Have you seen this issue in the general case? Or only when dealing with an instruction followed by a jump?

**Comment by 10110111** [comment]
Well, disassembly:
````
mov ecx, 0x12345
nop
nop
nop
loop firstNop
````

**Comment by 10110111** [comment]
Not sure about general case, but each time I tried using conditional breakpoint functionality it behaved similarly — stuck at the breakpoint.

**Comment by eteran** [comment]
Oh, I forgot that `loop` decrements `rcx`, so it should hit **eventually**. Is it possible that, it's just slow?

**Comment by 10110111** [comment]
No, each time I press `F11` after `F9`, `ecx` decreases exactly by one.

**Comment by eteran** [comment]
OK, weird, yea it is just sitting on the BP, even though it thinks it resumed it isn't actually running.

**Comment by 10110111** [comment]
Well both debuggee and EDB take whole CPU core, so they both seem to do something there :)

**Comment by eteran** [comment]
OK, well I know they used to work. I'll have to look into the resume code and see what's going on. It is definitely a weird one.

**Comment by eteran** [comment]
Thought about it, and I have a hypothesis on what the issue is. First some background:

Resuming a BP is annoyingly complex. When you are stopped on a BP and want to run. You need to do the following:

1. back up one byte, because the CPU actually executed the BP instruction, moving the IP past it.
2. disable the BP.
3. **step** 1 instruction. We can't just resume, because what if the BP was on a jump to itself or some other situation where this BP can be hit again.
4. re-enable the BP.
5. finally resume.

This clearly works correctly for the manually controlled case of hitting stop and hitting run. But I am willing to bet, that somehow step 3 is not being done for conditional BPs. This explains the 100% usage by both edb and debuggee.

* edb is constantly receiving a BP, stepping back 1 byte, resuming, hitting it again (with no progress)
* the debuggee is constantly running and hitting the same BP over and over again (since edb keeps rewinding it to before the BP, and makes no progress).

I'll start reviewing the code, but I think it shouldn't be too bad to fix once the problem is properly identified.

**Comment by 10110111** [comment]
Do you mean step **2** is not being done?

**Comment by eteran** [comment]
no, i think that 3 isn't being done, i think that it is: 

* backing up 1 byte
* disabling the BP
* re-enabling the BP
* then resuming (thus just trigger the BP again with no progress)

**Comment by 10110111** [comment]
Hmm, in fact, I haven't even found disabling and re-enabling the BP in `Debugger::handle_trap()`. Seems it just "jumps" back one byte and if the condition is false, continues.

**Comment by eteran** [comment]
interesting, I'm going to get some lunch, and think some more on it. But I think we're narrowing down on the issue.

**Comment by eteran** [comment]
So `handle_trap` returns `DEBUG_CONTINUE`. Which should eventually boil down to a call to `resume_execution(..., MODE_RUN)`.

**That** code looks like it is trying to take measures to track which BP to re-enable, and step. Once, we get the next event, if `renable_breakpoint_step_` is set, it should enable that BP and then resume as normal.

So it **looks** like it should work, but I'll need to do some debugging to track where it's going wrong :-(

**Comment by eteran** [comment]
got it, the code path was passing the `force` flag, which prevents the BP related code from executing during the resume. So to make the change minimal, I added a new return code to mean "i'm ignoring this BP", and have that code do the right thing. Reopen if this fix seems insufficient.

**Comment by 10110111** [comment]
OK, this does seem to work now. It's awfully slow, but still this particular bug is solved.

**Comment by eteran** [comment]
Yea, the conditional BPs aren't amazingly fast. It's comparable to stopping the debugee and holding down the F7 (to very rapidly step). It is possible that we are paying for a refresh of the GUI each hit too (which we should attempt to avoid if that is in fact the case).

**Comment by 10110111** [comment]
Anyway, this is a thing for another issue. First of all we'll need to profile what takes the most CPU time.
