### ISSUE TITLE
proc-pid-mem-write.h

### ISSUE THREAD

**Issue by Aut0matA** [eteran/edb-debugger#319]
I can't find the header file "proc-pid-mem-write.h" anywhere. I hope this is the correct place to post this.

**Comment by eteran** [comment]
Are you encountering a build error? If so, please paste it if you can.

Iit should be generated during the build process. @10110111 is the author of that particular piece of code, so he's probably best able to address this question.

**Comment by eteran** [comment]
Also, if you are attempting an out of source build, I believe that there is currently an issue with that with regards to that generated file.

**Comment by eteran** [comment]
I just pushed a commit which I believe fixes out of source builds. Please let me know if this addresses your issue.

**Comment by Aut0matA** [comment]
Indeed it did. Thanks so much, and wow what a fast response.

**Comment by 10110111** [comment]
@eteran it seems build instructions have to be updated until we find a way to fix this...

**Comment by Aut0matA** [comment]
@10110111 now i feel like a dolt, I believe my problem wasn't with the .pro file but with PlatformProcess.cpp. I didn't notice at first but the directive was #include "procPidMemWrites.h" and not #include "detect/procPidMemWrites.h". I only noticed afterwards when I applied the changes. So there was a mismatch with the pro file and the include directive, this was from a new clone of the project.

**Comment by eteran** [comment]
@Aut0matA, actually it used to be `#include "detect/procPidMemWrites.h"`, but I changed it to `#include "procPidMemWrites.h"` make it simpler to change where the generated file would end up, so long as it ends up in the include path. So you weren't wrong when you wrote this issue!

Now it places the file in a directory relative to the output directory, instead of relative to where qmake was run. So all should be good now :-).
