### ISSUE TITLE
FIP/FDP value editor shows "bad1" to the user in some cases

### ISSUE THREAD

**Issue by eteran** [eteran/edb-debugger#322]
When I open up /bin/ls and immediately pull up the editor for either FIP or FDP in the Registers view. I am presented with values such as:

    -BAD bad1 00000000 00000000

and

    bad10000000000000000

Dispite the Register view showing the user `0000:0000000000000000`. These `bad1` values are internal sentinels which are not supposed to be visible to the user.

**Comment by 10110111** [comment]
It's because we launch DialogEditFPU for any FPU register. But this will be broken anyway for such presentation — it's not just FIP/FDP, but rather FIS:FIP/FDS:FDP. I'd rather fix this (if still needed) after switch to new register view. For now it'd be enough to check in ArchProcessor::edit_item that item's name isn't FIP nor FDP.

**Comment by 10110111** [comment]
This must have been fixed by recent merge.
