### ISSUE TITLE
Stepping into clone() system call makes EDB think debuggee has terminated

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#345]
Here's a simple test program:
````
#include <pthread.h>

void* threadFunc(void* p)
{
    for(volatile int x=0;x<99999999;++x);
    return 0;
}

int main()
{
    pthread_t newThread;
    pthread_create(&newThread,NULL,threadFunc,NULL);
    pthread_join(newThread,0);
    return 0;
}
````

If you launch it in EDB, break on `__clone` and step into its `int 0x80` instruction with F7, you'll get "The application has terminated" message, although if you instead run till the next instruction using F4, you'll get the expected results.

**Comment by eteran** [comment]
interesting, I'll look into this.

**Comment by eteran** [comment]
So, on my machine, the example program gets literally optimized into essentially nothing. There is no call to `__clone` that gets generated. I had to put a `sleep(1)` to have it even create a call to `pthread_create`.

Once I've done that, I was able to put a breakpoint in the `__clone` function which appears to work correctly. However, it used `syscall` instead of `int 0x80`.

So, I'm not sure if this is a reproducable/real issue. When you get a chance, confirm?

**Comment by 10110111** [comment]
Oh, that's strange. What compiler did you use? Also, did you specify any optimization options? And `syscall` should mean that you're testing it on x86_64. I tested on x86, will check what happens on 64 bits.

**Comment by eteran** [comment]
Yea, amd64 arch. Using gcc 4.9.0.

**Comment by 10110111** [comment]
Hmm, added three more nines in the loop, and indeed, I was wrong. It just appears to exit very fast with EDB. So it seems this one is invalid, or I've made too small a minimal example to show actual bug :)
