### ISSUE TITLE
Latest commit using QDesktopServices::storageLocation breaks QT5 compability

### ISSUE THREAD

**Issue by lxj616** [eteran/edb-debugger#354]
Configuration.cpp: In member function ‘void Configuration::read_settings()’:
Configuration.cpp:110:27: error: ‘storageLocation’ is not a member of ‘QDesktopServices’
  QString cacheDirectory = QDesktopServices::storageLocation(QDesktopServices::CacheLocation);
                           ^
Configuration.cpp:110:61: error: ‘CacheLocation’ is not a member of ‘QDesktopServices’
  QString cacheDirectory = QDesktopServices::storageLocation(QDesktopServices::CacheLocation);
                                                             ^
Makefile:1034: recipe for target '.release-shared/obj/Configuration.o' failed

There are documentations here:

https://wiki.qt.io/Transition_from_Qt_4.x_to_Qt5

`QDesktopServices::storageLocation deprecated`

**Comment by njfox** [comment]
Changing line 110 in Configuration.cpp from:
`QString cacheDirectory = QDesktopServices::storageLocation(QDesktopServices::CacheLocation);`

to:
`QString cacheDirectory = QStandardPaths::standardLocations(QStandardPaths::CacheLocation)[0];`

and recompiling seems to have resolved the issue for me. I'm hesitant to submit a pull request since I won't have much time to do any regression testing. Would anyone mind checking out this fix?

**Comment by eteran** [comment]
Ah, should have tested on Qt5 first! I'll get a patch in right away.
