### ISSUE TITLE
is_nop in ROP gadget finder

### ISSUE THREAD

**Issue by mrexodia** [eteran/edb-debugger#457]
The `is_nop` https://github.com/eteran/edb-debugger/blob/master/plugins/ROPTool/DialogROPTool.cpp#L38 function could benefit from https://github.com/x64dbg/capstone_wrapper/blob/master/capstone_wrapper.cpp#L286

**Comment by eteran** [comment]
Ah good call, I'll check that out :-)

**Comment by eteran** [comment]
Took a look at the code, I think your code looks great and we'll definitely try to import it. At the moment, our Capstone wrapper suffers from a bit of messiness due to trying to be consistent with our original custom disassembly engine. I think we'll want to clean that up first.

Thanks for the pointer though!
