### ISSUE TITLE
Selection can go outside Disassembly viewport while step-tracing

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#525]
When the lowest line in the disassembly is partially visible, the view doesn't autoscroll on selection moving there (e.g. when using arrow keys or tracing debuggee). It only appears to scroll when the selection gets out of viewport completely (i.e. one line lower). Thus you get result like this:
![scrn1](https://cloud.githubusercontent.com/assets/6376882/21345107/e4a93844-c6af-11e6-83c8-036b2ab909d3.png)

**Comment by AaronOpfer** [comment]
Hmm, that's probably from my recent changes to the scrolling and/or rendering. I believe it considers the very last partially visible line as a part of the viewport. I think we might want to implement something so that if the last line is not at least 75% visible vertically that we consider it outside of the viewport for the purposes of scrolling.

**Comment by 10110111** [comment]
Why not require it to be 100% visible? Reading a 75% line isn't very convenient.

**Comment by eteran** [comment]
Yea, the old code used to always round the number of lines to render down to avoid this issue.
