### ISSUE TITLE
x86 Debugging

### ISSUE THREAD

**Issue by TheOnlyRealTodd** [eteran/edb-debugger#536]
Hello,

I'm getting an error when I use edb.x86-64 to try and debug a 32 bit program, which says that I am using the 64 bit version and I should be using the 32 bit version. Is there a separate repository/release specifically for x86 only? On dnf all I see is the x86-64 version. Thanks.

**Comment by 10110111** [comment]
You shouldn't have any such error. Could you cite the exact text of the error?

**Comment by TheOnlyRealTodd** [comment]
I'll update tonight when I get back on the machine in question. Thanks!

**Comment by eteran** [comment]
Also, are you using the latest version? This used to be a restriction, but was gotten rid of about a year ago by @10110111's work.

**Comment by TheOnlyRealTodd** [comment]
![edb-error](https://cloud.githubusercontent.com/assets/19983799/22350408/84ab3f7e-e3c8-11e6-9f4c-64674e59c6c4.png)
And yes I have used dnf. I am on version 0.9.18. Sorry, I am new to Fedora, should I not be using dnf? Is there a better package manager? Thanks.

**Comment by eteran** [comment]
OK, yea, the fedora packages (like most, not completely their fault) are a bit out of date. My recommendation is uninstall edb installed via dnf and then to use the latest from github by following the directions found here:

https://github.com/eteran/edb-debugger/wiki/Compiling-(Fedora)

Please be sure to either update the settings in edb on first launch or more simply just delete the config file, so that it won't look in the wrong location for the plugins:

The config file is found at:

    ~/.config/codef00.com/edb.conf

**Comment by TheOnlyRealTodd** [comment]
@eteran awesome, thank you so much!
