### ISSUE TITLE
Registers pointing to visible address may take more space than allocated in the Disassembly View

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#552]
And I can't really move the address column. See this screenshot:

![scrn](https://cloud.githubusercontent.com/assets/6376882/25656098/2c2da682-3000-11e7-9782-e269422e4d9c.png)

**Comment by AaronOpfer** [comment]
Maybe the blank space on the left should only be allocated if there is a
badge, and be sized to the largest badge. It would make the GUI possibly
change size as it is scrolled which is not wonderful, but most of the time
it makes the badges take less space unless they actually need to show
something.

In addition, right clicking on the badge area should give you a context
menu to disable the setting so that when new users "discover" the feature
suddenly they don't have to dig to get rid of it.
