### ISSUE TITLE
when plan for windows

### ISSUE THREAD

**Issue by cxj98** [eteran/edb-debugger#553]
long time waitting has no message, we need for windows version, thans.

**Comment by eteran** [comment]
I am going to close this since it is simply a question. But I'll also answer as best I can:

Firstly, please track issue #261 since that is meant to track the porting progress in general. However, Linux is the only "supported platform" at the moment.

Of course, windows is planned, but I can't make any promises on the time frame. We will do our best to tackle it as soon as is feasible.
