### ISSUE TITLE
App Hangs on Debuggee Restart

### ISSUE THREAD

**Issue by AaronOpfer** [eteran/edb-debugger#557]
When I'm debugging an application I've analyzed and I attempt to Restart the application through edb's menu, edb freezes.

The console emits "Saving Session File" before the freeze occurs.

**Comment by eteran** [comment]
Is it all applications?

**Comment by AaronOpfer** [comment]
Not all applications. Looks like `/bin/ls` is fine, but some more sophisticated (threaded?) applications are not (like edb itself, for instance).

**Comment by eteran** [comment]
OK, was able to reproduce using edb on itself. Need to look into it further to figure out what the problem is :-/

**Comment by eteran** [comment]
I believe that this is a variant of issue #382 , and have applied the fix recommended there. Unfortunately, edb does have some quirks with threaded debugging still. Reproducing this bug repeatedly would occasionally cause edb to fail to properly trace the child process. So that is something else that will need to be looked into.
