### ISSUE TITLE
Stepping over an instruction sometimes appears to step "backwards"

### ISSUE THREAD

**Issue by AaronOpfer** [eteran/edb-debugger#616]
Very occasionally when stepping over a normal-looking function preamble after it trips a breakpoint, the function appears to step "backwards":

![image](https://user-images.githubusercontent.com/1189089/31050700-7d0a9176-a618-11e7-8769-dc2284b7a808.png)

I step over once:

![image](https://user-images.githubusercontent.com/1189089/31050708-8e593ca2-a618-11e7-8c77-c3d102ab8089.png)

Then I step over again:

![image](https://user-images.githubusercontent.com/1189089/31050711-9d6cd62c-a618-11e7-99e1-acf4c3384119.png)

And I'm back at my original breakpoint for some reason. Stepping over again repeats this again, and in this case since I'm constantly repeating the PUSH instructions I break the stack and segfault the application shortly after.

~Using "Step Into" does not demonstrate this behavior.~

**Comment by 10110111** [comment]
This actually always happens if you try stepping over (and into!) an instruction following another instruction on which a breakpoint is set. This is because EDB tries to find a breakpoint which might have resulted in the trap, and then rewinds the instruction pointer to re-run the instruction.
Simple debuggee code to reproduce the problem:
```
nop      # a breakpoint here
push edi
```
In a fix, EDB should check actual trap reason, and if it's single-stepping, then no rewinding should be done.
