### ISSUE TITLE
Native open dialog instead of Qt

### ISSUE THREAD

**Issue by Az404** [eteran/edb-debugger#637]
There is a problem with Open dialog on Kali 2016.2: dialog shows as system default, instead of custom Qt version with "arguments" and "working directory" fields.

![open_dialog](https://user-images.githubusercontent.com/17743197/34391258-4f9c394a-eb66-11e7-81c0-f975d044a648.png)

This warning shown on Debugger Error Console after dialog opening:
WARN   "Failed to setup program arguments and working directory entries for file open dialog, please report and be sure to tell your Qt version"

edb version is 0.9.22, latest commit 4888562 from master
Qt version is 5.9.2

**Comment by 10110111** [comment]
Hmm, this doesn't look too Qt-ish. Is it a GTK dialog somehow forced on Qt applications?..

**Comment by eteran** [comment]
That is definitely a GTK themed dialog

**Comment by 10110111** [comment]
OK, the culprit is `qt5-gtk-platformtheme` package, namely the file `/usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/libqgtk3.so`. If you remove the package, you'll get the good old Qt file open dialog, where EDB's customizations work as expected.

I don't think we can do anything good about this: the [docs on `QFileDialog`](https://doc-snapshots.qt.io/qt5-dev/qfiledialog.html#Option-enum) clearly say:

> `QFileDialog::DontUseNativeDialog`: Don't use the native file dialog. By default, the native file dialog is used unless you use a subclass of QFileDialog that contains the `Q_OBJECT` macro, or the platform does not have a native dialog of the type that you require.

EDB's `DialogOpenProgram` is exactly a subclass of `QFileDialog` with `Q_OBJECT` macro in its declaration.

**Comment by Az404** [comment]
It helps, thanks!
