### ISSUE TITLE
hello, author. does it have windows compiling version?

### ISSUE THREAD

**Issue by cxj98** [eteran/edb-debugger#654]
hello, author. does it have windows compiling version? thanks.

**Comment by eteran** [comment]
Sort of... we do have things set up such that appveyor tests that the code **compiles** on windows. But I will have to check into how functional of a state the actual debugging capabilities are.

**Comment by AaronOpfer** [comment]
As an aside, I'd love to have a step by step guide to getting a development
environment set up on a Windows box. I wanted to check in out myself but
got too frustrated after a few hours trying to figure it out. :)

**Comment by eteran** [comment]
I think that the best bet is reconstructing what the AppVeyor script does since it successfully creates at least a basic windows build (I imagine many plugins are not included in the compile).

I am closing this "issue" since it is more of a question than a problem, and the answer is "not yet in any meaningful way".
