### ISSUE TITLE
Cannot Open Binary in edb (execv() failed: Permission denied)

### ISSUE THREAD

**Issue by zachsis** [eteran/edb-debugger#679]
Just compiled edb-debugger on fedora 26 to give it a spin. I'm getting the following error when trying to open a PE file: 

Failed to open and attach to process:
execv() failed: Permission Denied

I also tested with `setenforce 0`, and `sudo edb`. Same result

**Comment by eteran** [comment]
edb can only debug applications which your native OS can run. PE files are not executable on linux.

**Comment by Keskebeu** [comment]
so what files can the debugger attach. I get the same output when I run Linux native files.

**Comment by 10110111** [comment]
At least those which can be executed. Namely, they must have run permission set for the user trying to run them.

**Comment by Keskebeu** [comment]
I made it work. I needed xterm. But still some files cannot be executed
like .txt or .png. But .py file do.

On Dec 16, 2018 11:52 AM, "Ruslan Kabatsayev" <notifications@github.com>
wrote:

At least those which can be executed. Namely, they must have run permission
set for the user trying to run them.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/eteran/edb-debugger/issues/679#issuecomment-447658151>,
or mute the thread

**Comment by 10110111** [comment]
>But still some files cannot be executed like .txt or .png.

Erm... they are not supposed to ever be executed.
> But .py file do.

For `.py` the interpreter gets executed under EDB.
