### ISSUE TITLE
Feature: Shortcut for Attach

### ISSUE THREAD

**Issue by ttufts** [eteran/edb-debugger#683]
When it is necessary to constantly detach and reattach to a process, navigating via menus is terrible. Give me keyboard shortcuts!

**Comment by 10110111** [comment]
Why such a demanding tone? This is an opensource project, it's developed in contributors' own free time. Such a tone doesn't help motivate to implement the features requested.
And, BTW, the users are welcome to propose patches implementing the functionality they need. This can help getting the features sooner than it would be otherwise.

**Comment by eteran** [comment]
@10110111 He's actually a friend of mine, so he's just busting my chops :-).

**Comment by eteran** [comment]
Since `F3` starts a new process, `Shift+F3` will now attach to a process. Enjoy your shortcut :-P
