### ISSUE TITLE
Error assembling instruction

### ISSUE THREAD

**Issue by ViRb3** [eteran/edb-debugger#728]
Built fresh from master

```asm
movabs rdx, 0x67616c666c6f6f63
```

- yasm:
`/tmp/edb_asm_temp_10446_iDxRLj.asm:6: error: instruction expected after label`
- nasm:
`/tmp/edb_asm_temp_10446_KRDakW.asm:6: error: parser: instruction expected`
- fasm:
```
/tmp/edb_asm_temp_10446_ienKvb.asm [6]:
		movabs rdx, 0x67616c666c6f6f63
processed: movabs rdx,0x67616c666c6f6f63
error: illegal instruction.
```

**Comment by 10110111** [comment]
That's expected. EDB doesn't currently try to make its disassembly round-trip with any of its supported assemblers. You have to fixup the mnemonic to match the expectations of your particular assembler. In this case, use `mov` instead of `movabs`.

**Comment by eteran** [comment]
I'm closing this issue because edb currently makes no effort to support this due to the fact that we leverage external utilities for assembling.

@ViRb3 I can't promise that making the assembler input and disassembly compatible with each other is a feature we'll implement any time soon, but it is certainly something we will continue to be aware of.

Thanks!
