### ISSUE TITLE
Means of colloborating

### ISSUE THREAD

**Issue by SourceCodeDeleted** [eteran/edb-debugger#768]
This is quite a nice product!

Do you have a discord or some chat for collaboration?

**Comment by eteran** [comment]
Hello!

So, the answer is "sort of", we have a [gitter](https://gitter.im/eteran/edb-debugger), but to be honest... because it's web-based, I don't tend to check it that often.

I actually like the idea of creating a discord for it. @10110111 does that sound good to you too? Even though dev has been slower in 2020 that in the past, I like the idea of being able to at least have the option of real-time collaboration and discussion!

**Comment by 10110111** [comment]
@eteran 
I don't actually see much benefit of realtime chat for this project. It's not that active to need this. But if someone feels the need to chat, I wouldn't be against the idea. Just would like to make sure the platform doesn't require the user to disclose a phone number to it (like WhatsApp, Viber, Telegram, new GMail accounts, etc. require).

Gitter seems to have worked in the past (I had even forgotten I chatted there with you, your link reminded :D). You mention that you "don't check" it: does it not support email notifications? I don't think I would actively check any other platform either—be it web-based or not. There must be some kind of ping to synchronize the beginning of a conversation.

**Comment by eteran** [comment]
So, you're right that the project isn't really that active in terms of engagement with users and possible contributors. But I was thinking, maybe there is an opportunity to create more interaction 🤷 

As for Gitter, yea it definitely does email notifications, but things like discord are much more popular and actually have a proper app for mobile and desktop, meaning we could, at least in theory be able to respond to things "whenever and wherever" without much extra effort.

But, I totally see your point, I'm not decided to do it, but I do admittedly like the idea. I'll think about it. For now, @SourceCodeDeleted I'll be keeping an eye out for you on our Gitter and will be happy to chat if you have any comments questions or other types of contribution you'd like to make!

I'm going to close this issue since the question has been answered, but If we decide to start something like a Discord, I'll update it with the necessary information.
