### ISSUE TITLE
libDebuggerErrorConsole

### ISSUE THREAD

**Issue by HBLocker** [eteran/edb-debugger#807]
I saw this error message in the console
``
load_plugins] Cannot load library /usr/lib/x86_64-linux-gnu/edb/libDebuggerErrorConsole.so: (/usr/lib/x86_64-linux-gnu/edb/libDebuggerErrorConsole.so: undefined symbol: _ZN26DebuggerErrorConsolePlugin20DebuggerErrorConsole20compareDisassemblersEv)
Starting edb version: 1.0.0
Please Report Bugs & Requests At: https://github.com/eteran/edb-debugger/issues
qt5ct: D-Bus global menu: no
comparing versions: [4864] [4096]
Running Terminal:  "/usr/bin/xterm"
Terminal Args:  ("-title", "edb output", "-hold", "-e", "sh", "-c", "tty > /tmp/edb_temp_file_1453610291_174388;trap \"\" INT QUIT TSTP;exec<&-; exec>&-;while :; do sleep 3600; done")
Terminal process has TTY:  "/dev/pts/9"
``

**Comment by eteran** [comment]
This looks to me like it was installed via a package. Or at least the plugins it is finding were.

Given that 1.0.0 is a pretty old version of edb, I would recommend uninstalling that version completely. Deleting the `~/.config/codef00.com/edb.conf` and compiling the master branch from source and seeing if that runs correctly for you.

All of that being said, does edb work correctly otherwise?

**Comment by HBLocker** [comment]
Thank you for the quick reply! yeah it works fine and I really it!

**Comment by eteran** [comment]
Excellent. Closing the issue, please reopen if you continue to have an issue.
